pro:
  auth_token: FpDtMx6J3lwbIo6BW_tdqg
  repositories:
    timetrack: neo/neo-timetrack
    prickly_puma_rails: neo/prickly-puma-rails
    world-trainer: neo/world-trainer
    spotlight: neo/spotlight
    catherd: neo/catherd
  type: pro
